### ISSUE TITLE
Problems with matroska files

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#209] opened 2021-03-10 08:21 UTC
I am trying to work with a matroska container (.mkv) with mjpeg content, but MgObject chokes: 

```~/anaconda3/lib/python3.7/site-packages/musicalgestures/_utils.py in get_framecount(filename, fast)
   1035             raise FileNotFoundError(out.splitlines()[-1])
   1036         else:
-> 1037             return int(out)
   1038 
   1039     else:

ValueError: invalid literal for int() with base 10: 'N/A\n'
```

Would be good to be able to use mkv files, I think. In fact, we may consider changing from .avi to .mkv as the internally produced container.

**Comment by balintlaczko** [comment] 2021-04-04 17:46
Will look into this now. 

The problem is that - as far as I remember, it's been a while since I researched this - you cannot guarantee cross-platform stable behavior with any other container than avi. Some containers work well on a particular platform but won't work on others, and avi seems to work on all platforms. (This has been a huge issue with opencv-python, for almost a decade, and a lot of devs have been complaining about it.)

**Comment by balintlaczko** [comment] 2021-04-04 18:09
Confirmed, this is due to my way of querying ffprobe about the frame count of the video, as described [here](https://stackoverflow.com/questions/2017843/fetch-frame-count-with-ffmpeg). I only implemented the fast method which - as they also point out - does not work with mkv. I will extend the code to accommodate mkv files too with another method.

**Comment by balintlaczko** [comment] 2021-04-04 18:24
This is fixed now.

**Closed by balintlaczko** 2021-04-04 18:24 UTC
Labels: bug
